import streamlit as st
import plotly.graph_objects as go

# --------------------------------------------------
# Page Configuration
# --------------------------------------------------

st.set_page_config(
    page_title="AI-Based Precision Farming",
    page_icon="🌱",
    layout="wide"
)

# --------------------------------------------------
# Custom CSS
# --------------------------------------------------

st.markdown("""
<style>

#MainMenu {visibility:hidden;}
footer {visibility:hidden;}
header {visibility:hidden;}

.block-container{
    padding-top:2rem;
    padding-bottom:2rem;
}

.hero{
    background:linear-gradient(135deg,#2E7D32,#43A047);
    padding:55px;
    border-radius:20px;
    color:white;
    text-align:center;
    margin-bottom:30px;
}

.hero h1{
    font-size:46px;
    font-weight:bold;
}

.hero p{
    font-size:20px;
}

.feature{
    background:white;
    border-radius:15px;
    padding:25px;
    box-shadow:0 4px 15px rgba(0,0,0,.08);
    text-align:center;
    transition:.3s;
    border-top:5px solid #2E7D32;
}

.feature:hover{
    transform:translateY(-5px);
}

.badge{
    display:inline-block;
    background:#E8F5E9;
    color:#2E7D32;
    padding:8px 16px;
    border-radius:20px;
    margin:5px;
    font-weight:bold;
}

.footer{
    text-align:center;
    color:gray;
    padding:20px;
}

</style>
""", unsafe_allow_html=True)

# --------------------------------------------------
# Sidebar
# --------------------------------------------------

st.sidebar.title("🌾 Navigation")

st.sidebar.success("🏠 Home")

st.sidebar.info("🌾 Crop Recommendation")

st.sidebar.info("🌱 Fertilizer Recommendation")

st.sidebar.markdown("---")

st.sidebar.subheader("📌 Project Highlights")

st.sidebar.markdown("""
- 🤖 Random Forest Models
- 🌾 Crop Recommendation
- 🌱 Fertilizer Recommendation
- 📈 Prediction Confidence
- 📊 Top 5 Recommendations
""")

st.sidebar.markdown("---")

st.sidebar.caption("AI-Based Precision Farming Recommendation System")

# --------------------------------------------------
# Hero Section
# --------------------------------------------------

st.markdown("""
<div class="hero">
<h1>🌱 AI-Based Precision Farming Recommendation System</h1>
<p>
Empowering Smart Agriculture using Machine Learning for Intelligent Crop and Fertilizer Recommendations
</p>
</div>
""", unsafe_allow_html=True)

# --------------------------------------------------
# Metrics
# --------------------------------------------------

m1, m2, m3= st.columns(3)

m1.metric("🌾 Crop Accuracy", "99.55%")
m2.metric("🌱 Fertilizer Accuracy", "87.50%")
m3.metric("🤖 Models", "5")

st.divider()

# --------------------------------------------------
# Features
# --------------------------------------------------

st.subheader("🚀 What This System Can Do")

col1, col2 = st.columns(2)

with col1:
    st.info("""
### 🌾 Crop Recommendation

Recommend the most suitable crop based on soil nutrients and environmental conditions.
""")

    st.info("""
### 🌱 Fertilizer Recommendation

Suggest the optimal fertilizer for healthy crop growth.
""")

with col2:
    st.info("""
### 📈 Prediction Confidence

View prediction confidence scores and the Top 5 recommendations generated by the machine learning models.
""")

    st.info("""
### ⚡ Instant Prediction

Generate intelligent recommendations within seconds using trained Random Forest models.
""")

# --------------------------------------------------
# Model Performance
# --------------------------------------------------

st.header("📈 Final Model Performance")

fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=["Crop Model", "Fertilizer Model"],
        y=[99.55, 87.50],
        text=["99.55%", "87.50%"],
        textposition="outside",
        marker_color=["#2E7D32", "#66BB6A"]
    )
)

fig.update_layout(
    template="plotly_white",
    height=450,
    yaxis=dict(range=[0, 105]),
    xaxis_title="Random Forest Models",
    yaxis_title="Accuracy (%)"
)

st.plotly_chart(fig, use_container_width=True)

st.divider()

# --------------------------------------------------
# Workflow
# --------------------------------------------------

st.header("🌾 System Workflow")

w1, w2, w3, w4 = st.columns(4)

w1.success("1️⃣\n\nEnter\nParameters")
w2.info("2️⃣\n\nCrop\nRecommendation")
w3.warning("3️⃣\n\nFertilizer\nRecommendation")
w4.success("4️⃣\n\nView\nResults")

st.divider()

# --------------------------------------------------
# Technologies
# --------------------------------------------------

st.subheader("🛠️ Technologies Used")

st.markdown("""
- Python
- Pandas
- NumPy
- Scikit-learn
- Matplotlib
- Streamlit
- Joblib
""")

st.divider()

# --------------------------------------------------
# Footer
# --------------------------------------------------

st.markdown("""
<div class="footer">
<b>Developed by Dilpreet Kaur</b><br>
B.Sc. IT Major Project • AI-Based Precision Farming Recommendation Engine
</div>
""", unsafe_allow_html=True)